'use strict'

const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const { test } = require('node:test')
const { pathToFileURL } = require('node:url')
const ROOT = path.resolve(__dirname, '../..')

// Real consumer compilation: every negative line must fail, every other line must pass.
// No ts-ignore/expect-error directives or regex-only type assertions.
test('shared APIs, entities, callbacks and Vue events reject invalid consumers', async () => {
  const dir = path.join(ROOT, '.artifacts/ts-contract-review')
  await fs.mkdir(dir, { recursive: true })
  const source = [
    "import { createApplication, getApplication, updateApplication, advanceApplication, getApplicationStatus } from '../../utils/applicationMockApi'",
    "import { getPetRoster } from '../../utils/petRosterMockApi'",
    "import { getFeedingOrders } from '../../utils/feedingOrderMockApi'",
    "import type { FeedingOrderItem } from '../../utils/feedingOrderMockApi'",
    "import { formatFeedbackTimeout } from '../../utils/feedingOrderMockApi'",
    "import { getPawHomeYardPetById } from '../../utils/yardMock'",
    "import { getFeedingOrderDetail as getMockFeedingOrderDetail } from '../../utils/feedingOrderMockApi'",
    "import { getFeedingOrderDetail, getFeedingOrders as getServiceFeedingOrders } from '../../packages/feeding/services/orderMockApi'",
    "import { hideOrderForUser, setOrderHidden } from '../../packages/feeding/services/orderVisibilityStorage'",
    "import { applyRescueReviewAction, readRescueReviewDetail, readRescueReviewList } from '../../packages/rescue/services/reviewActionAdapter'",
    "import { resolveProductionDeepLink } from '../../navigation/productionDeepLinkResolver'",
    "import { createDeepLink, createTaskDeepLink, restoreAfterAuth } from '../../navigation/deeplinkContracts'",
    "import { saveAuthContinuation } from '../../navigation/authContinuationStorage'",
    "import { feedbackBusinessKey, feedbackRequestKey } from '../../navigation/feedbackContracts'",
    "import { evaluateSocialMutation } from '../../navigation/socialMutationContracts'",
    "import { createAdoptionTransitionContract } from '../../navigation/adoptionConditionContract'",
    "import { canReadFeedbackTask, getFeedbackTaskAccess } from '../../navigation/feedbackContracts'",
    "import { saveRewardOrder } from '../../navigation/orderContracts'",
    "import { canOrderAction, findGiftOrderByApplicationId, isOrderHiddenForUser, ORDER_OPERATIONS, rewardAssociationKey, visibilityKey } from '../../navigation/orderContracts'",
    "import { getAdoptionMineStatusTone } from '../../packages/adoption/services/mineMetadata'",
    "import { getAdoptionQuotaTitle } from '../../packages/adoption/services/quotaMetadata'",
    "import { getRescueApplicationStatusPresentation } from '../../packages/rescue/services/componentMetadata'",
    "import { getRescueMineStatusPresentation } from '../../packages/rescue/services/mineMetadata'",
    "import { createFeedingOrderToolbarState } from '../../packages/feeding/services/orderListMetadata'",
    "import { getAddressById, deleteAddress, setDefaultAddress } from '../../utils/addressMock'",
    "import { setRealNameVerified } from '../../utils/realNameMock'",
    "import { getMemberLevelTitle } from '../../utils/memberLevel'",
    "import { getJuryVote, writeJuryVote, writeJuryVotes, getJuryItemsByStatus, getJuryItemById, getNextJuryItem } from '../../utils/juryStorage'",
    "import { getJuryMockItemById, getJuryMockConfig } from '../../utils/juryMock'",
    "import { readPublicProfile, updateLocalProfile } from '../../packages/account/services/localProfileStorage'",
    "import { readOrderById, readGiftOrderByApplicationId } from '../../packages/feeding/services/orderAdapter'",
    "import { readOrderList } from '../../packages/feeding/services/orderAdapter'",
    "import type { OrderListData, OrderResult } from '../../packages/feeding/services/orderAdapter'",
    "import { findRewardOrderById, findRewardOrderByApplicationId, writeRewardOrders } from '../../utils/rewardOrderStorage'",
    "import { findRegionOptions, findRegionPath } from '../../utils/regionMock'",
    "import { getAdoptionById, setLastAdoptionId, addAdoption, updateAdoption, transitionAdoption } from '../../utils/adoptionStorage'",
    "import { getRescueById, createRescue, updateRescue, transitionRescueApplication, addRescueProof, hasRescueProofByUser, canManageRescue, getRescueReviewSummary } from '../../utils/rescueStorage'",
    "import { readProfile, readManagementResource, readManagement, readManagementResourceWithReader, createManagementAdapter } from '../../packages/account/services/managementAdapter'",
    "import { updateProfile, updateYard, updateAnimal, updateManagementResource } from '../../packages/account/services/managementMutationAdapter'",
    "import { readEditorResource, saveEditorResource } from '../../packages/account/services/managementEditorRuntime'",
    "import { readPublicYard, updateLocalYard } from '../../packages/yard/services/localManagementStorage'",
    "import { readEditorResource as readYardEditorGate } from '../../packages/yard/services/managementEditorGate'",
    "import { readPublicAnimal, updateLocalAnimal, createLocalAnimal } from '../../packages/animal/services/localManagementStorage'",
    "import { readEditorResource as readAnimalEditorGate } from '../../packages/animal/services/animalManagementEditorGate'",
    "import { readPrivate, writeWithCapability, createCapabilityEvaluator } from '../../navigation/actorCapabilities'",
    "import type { AdoptionRecord, RescueRecord } from '../../contracts/applications'",
    "import { readAdoptionApplication } from '../../packages/adoption/services/applicationAdapter'",
    "import { readAdoptionApplicationWithResolver } from '../../services/domainReads/adoption/applicationAdapter'",
    "import { readAdoptionReviewList, readAdoptionReviewDetail } from '../../services/domainReads/adoption/reviewAdapter'",
    "import { readRescueStateById, readRescueStateWithResolver } from '../../services/domainReads/rescue/stateAdapter'",
    "import { readRescueMine, readRescueReviewList as readDomainRescueReviewList } from '../../services/domainReads/rescue/lists'",
    "import { readAccountTasks } from '../../packages/account/services/taskAdapter'",
    "import { readDynamicRecord } from '../../packages/dynamic/services/reader'",
    "import { getFeedingOrders as getFeedingOrderPicker } from '../../packages/dynamic/services/orderPicker'",
    "import { animalIdsOfOrder, isFeedbackEligible } from '../../packages/dynamic/services/orderAssociation'",
    "import { readPersistedOrderDetail } from '../../packages/feeding/services/orderRuntime'",
    "import { readFeedbackTaskList, readFeedbackTaskDetail } from '../../packages/feeding/services/feedbackAdapter'",
    "import { readFeedbackEvidence, appendFeedbackEvidence } from '../../packages/feeding/services/feedbackEvidenceStorage'",
    "import { readFeedingTaskSummaries } from '../../packages/feeding/services/taskReader'",
    "import { readRescueProofContext, submitRescueProof } from '../../packages/rescue/services/proof'",
    "import { readMessageById, appendMessage, produceLocalActionNotification, resolveMessageDestination, emitMessageDeepLink } from '../../packages/message/services/messageStore'",
    "import { publishLocalFeedback, publishLocalDynamic, readLocalFeedbackSummary } from '../../packages/dynamic/services/feedbackPublisher'",
    "type DynamicPublishFailure = Extract<Awaited<ReturnType<typeof publishLocalDynamic>>, { success: false }>; declare const dynamicPublishFailure: DynamicPublishFailure; const failureData: null = dynamicPublishFailure.data; void failureData",
    "import { readAdoptionProgress } from '../../packages/adoption/services/progress'",
    "import { statusPresentation } from '../../packages/adoption/services/progress'",
    "import { readRescueProgress } from '../../packages/rescue/services/progress'",
    "import { normalizedProofList, proofCount } from '../../packages/rescue/services/proof'",
    "import { recognizeAddress, parseAddressLocally } from '../../utils/addressService'",
    "import { getAnnouncementFeedingWeightJin } from '../../utils/announcementMetadata'",
    "import { asPawImageCssSize } from '../../components/base/pawImageMetadata'",
    "import { createDynamicMediaViewerItems } from '../../utils/dynamicMediaMetadata'",
    "import { readPawImageSourceUrl, readCompressedPawImageUrl, normalizePawImageDisplayMode } from '../../components/base/pawImageMetadata'",
    "import Search from '../../components/navigation/PawSearchBar.vue'",
    "import Marquee from '../../components/PawAnnouncementMarquee.vue'",
    "import AdoptPickCatsSheet from '../../components/AdoptPickCatsSheet.vue'",
    "import NineGrid from '../../components/libai-NineGridLayout/libai-NineGridLayout.vue'",
    "import PawRegionPicker from '../../packages/address/components/address/PawRegionPicker.vue'",
    "import PawSelectionSheet from '../../packages/animal/pages/editor/components/PawSelectionSheet.vue'",
    "import FeedingOrderDetailPage from '../../packages/feeding/pages/order/detail/index.vue'",
    "import YardCreatePage from '../../packages/yard/pages/create/index.vue'",
    "import type { YardRecorderStopEvent } from '../../utils/yardCreateMetadata'",
    "import { getAdoptionReviewList } from '../../utils/adoptionReviewMockApi'",
    "import PawImageCropper from '../../packages/yard/pages/create/components/form/PawImageCropper.vue'",
    "import AddressForm from '../../packages/address/components/address/PawAddressForm.vue'",
    "import AnimalDetailPage from '../../packages/animal/pages/detail/index.vue'",
    "import AnimalAlbumPage from '../../packages/animal/pages/album/index.vue'",
    "import { createAnimalAlbumItems } from '../../packages/animal/services/albumMetadata'",
    "import AdoptionReviewDetailPage from '../../packages/adoption/pages/review/detail/index.vue'",
    "import AdoptionJuryDetailPage from '../../packages/adoption/pages/jury/detail/index.vue'",
    "import Share from '../../components/ShareActionSheet.vue'",
    "import FixedBar from '../../components/layout/PawFixedActionBar.vue'",
    "import Comments from '../../components/dynamic/CommentThread.vue'",
    "import Toast from '../../packages/feeding/components/feedback/PawToast.vue'",
    "const result = getApplication('adoption', 'ad-1')",
    "if (result.success) { const record: AdoptionRecord = result.data; const media: string[] = record.mediaPaths }",
    "const rescue = getApplication('rescue', 'rescue-1'); if (rescue.success) { const record: RescueRecord = rescue.data; proofCount(record); normalizedProofList(record) }",
    "readProfile('user-1', { access: 'private' }); readManagementResource('animal', 'animal-1', { access: 'management' }); readManagement({ resourceType: 'yard', yardId: 'yard-1', access: 'public' })",
    "const managementAdapter = createManagementAdapter({ actorProvider: () => null, readers: { yard: locator => ({ yardId: locator.yardId || 'yard-1' }) } }); managementAdapter.readYard('yard-1')",
    "readManagementResourceWithReader('profile', 'user-1', { reader: locator => ({ userId: locator.userId }), actorProvider: () => null, policy: { profile: { readStates: ['active'] } } })",
    "updateProfile('user-1', { nickname: 'A', tags: ['helper'] }, { reader: locator => ({ userId: locator.userId, status: 'active', visibility: 'private' }), writer: context => context.next })",
    "updateYard('yard-1', { name: 'New yard', gallery: ['/yard.png'] }); updateAnimal('animal-1', { breed: '中华田园猫' }); updateManagementResource('animal', 'animal-1', { name: 'Mimi' })",
    "readEditorResource('yard', 'yard-1', { reader: locator => ({ yardId: locator.yardId }) }); saveEditorResource('animal', 'animal-1', { name: 'Mimi' })",
    "readPublicYard('yard-1'); updateLocalYard('yard-1', { name: 'New yard', location: '郑州' }); readPublicAnimal('animal-1', { yardId: 'yard-1' }); updateLocalAnimal('animal-1', { petValue: 15 }); createLocalAnimal('yard-1', { name: 'Mimi', breed: '英短', species: 'cat' }); readYardEditorGate('yard', 'yard-1'); readAnimalEditorGate('animal', 'animal-1')",
    "readAdoptionApplicationWithResolver('application-1', { actorProvider: () => null, perspective: 'applicant', resolver: context => ({ id: context.applicationId }) })",
    "readAdoptionReviewList({ actorProvider: () => null, reviewerRole: 'owner', filter: 'pending' }); readAdoptionReviewDetail({ actorProvider: () => null, reviewerRole: 'reviewer', applicationId: 'application-1', reviewItemId: 'review-1', perspective: 'reviewer' })",
    "readRescueStateById('rescue-1', { includeDemo: false }); readRescueStateWithResolver('rescue-1', { includeDemo: false, resolver: context => ({ id: context.rescueId }) })",
    "readRescueMine({ actorProvider: () => null, filter: 'platform_pending' }); readDomainRescueReviewList({ actorProvider: () => null, filter: 'processed' })",
    "readAccountTasks({ actorProvider: () => null, readers: { adoption: context => ({ items: [{ businessType: 'adoption', businessId: 'a', actorId: context.actor.id, actorRole: 'applicant', actionType: 'review', status: 'pending' }] }), rescue: context => [] } })",
    "readDynamicRecord('dynamic-1', { actor: { id: 'user-1' }, requireActor: false, allowPublic: true }); getFeedingOrderPicker({ variant: 'yard', yardId: 'yard-1', yardOwnerId: 'user-1' }); animalIdsOfOrder({ animalId: 'animal-1' }); isFeedbackEligible({ status: 'delivered' })",
    "readPersistedOrderDetail('order-1', { actorProvider: () => null, hiddenEntries: [{ userId: 'user-1', orderId: 'order-1', hidden: true }] })",
    "readOrderList({ actorProvider: () => null, source: 'reward', perspective: 'mine', yardId: 'yard-1', hiddenEntries: [] }); readRescueMine({ actorProvider: () => null, filter: 'all' }); createAdoptionTransitionContract({ pending: ['approved'] }); getFeedbackTaskAccess({ actorId: 'user-1' }, { actorProvider: () => ({ id: 'user-1', roles: [] }) }); canReadFeedbackTask({ actorId: 'user-1' }, { actorProvider: () => null })",
    "readFeedbackTaskList({ actorProvider: () => null, kind: 'dynamic', perspective: 'yard', yardId: 'yard-1', reader: context => [{ taskId: context.kind }] }); readFeedbackTaskDetail({ actorProvider: () => null, kind: 'feeding_evidence', taskId: 'feedback-task:order-1|animal-1' })",
    "const feedbackPolicy = { version: 'v1', evidenceKinds: ['dynamic'] as const, requiredCount: 0, maximumCount: 1, startsAt: null, expiresAt: null, countRules: { pending: 'exclude', active: 'exclude', corrected: 'exclude', deleted: 'exclude', withdrawn: 'exclude', rejected: 'exclude' } as const, lastFeedbackStates: ['active'] as const }; readFeedbackEvidence({ actorProvider: () => null, policy: feedbackPolicy, kind: 'dynamic', dynamicId: 'dynamic-1' }); appendFeedbackEvidence({ evidenceId: 'e-1', dynamicId: 'dynamic-1', kind: 'dynamic', actorId: 'user-1', policyVersion: 'v1', attemptKey: 'attempt-1', requestId: 'request-1', state: 'active', createdAt: Date.now() }, { actorProvider: () => null, policy: feedbackPolicy })",
    "readFeedingTaskSummaries({ actorProvider: () => ({ id: 'user-1', roles: ['owner'] }) })",
    "readRescueProofContext('rescue-1'); submitRescueProof('rescue-1', { name: 'A', relation: '邻居', note: '说明', idNo: '11010519491231002X', agreementChecked: true }, { actorId: 'user-1' })",
    "readMessageById('message-1', { actorProvider: () => null, category: 'system' }); appendMessage({ messageId: 'message-1', recipientId: 'user-1', category: 'system', title: '通知', preview: '', createdAt: '2026-01-01T00:00:00.000Z', businessType: 'adoption', businessId: 'application-1' }, { authorize: message => message.messageId === 'message-1' }); const messageResult = resolveMessageDestination('message-1', { actorProvider: () => null, readers: { adoption: context => ({ applicantId: context.actor.id }) }, authorize: context => context.record.applicantId === context.actor.id }); emitMessageDeepLink({ emit: (name, payload) => { void name; void payload } }, messageResult)",
    "produceLocalActionNotification({ action: { success: true, actorId: 'reviewer-1', applicationId: 'application-1', reviewItemId: 'review-1', toStatus: 'approved' }, recipientId: 'applicant-1', businessType: 'adoption', businessId: 'application-1', reviewItemId: 'review-1', category: 'system', title: '审核完成', authorize: context => context.actor.id === 'reviewer-1', actorProvider: () => null })",
    "publishLocalFeedback({ orders: [{ orderId: 'order-1' }], animals: [{ animalId: 'animal-1' }], content: '已投喂', mediaList: [{ url: '/feed.png' }], actorProvider: () => null, attemptKey: 'attempt-1', storage: { getStorageSync: () => null, setStorageSync: () => undefined } }); publishLocalDynamic({ content: '动态', media: ['/cat.png'], actorProvider: () => null, attemptKey: 'attempt-2' }); readLocalFeedbackSummary({ order: { orderId: 'order-1', yardId: 'yard-1' }, animal: { animalId: 'animal-1', yardId: 'yard-1' }, actorProvider: () => null })",
    "readAdoptionProgress('application-1', { actorProvider: () => null }); readRescueProgress('rescue-1', { actorProvider: () => null })",
    "statusPresentation({ status: 'pending' }); proofCount(null); normalizedProofList(null); recognizeAddress('张三 13800138000'); parseAddressLocally('张三 13800138000'); getAnnouncementFeedingWeightJin({ text: '投喂4斤' }); asPawImageCssSize(32); asPawImageCssSize('100%'); asPawImageCssSize(null); createDynamicMediaViewerItems(['/cat.png'], '/fallback.png')",
    "createApplication('adoption', { status: 'pending', pets: [{ id: 'p', name: '猫', avatar: '/cat.png' }], mediaPaths: ['/a.png'] })",
    "getPetRoster({ species: 'cat', managed: true, variant: 'yard' })",
    "const value: number = readPrivate('adoption.application.readPrivate', { object: { count: 1 } }, object => object.count)",
    "const promise: Promise<string> = writeWithCapability('adoption.application.write', { readObject: () => ({ id: 'a' }) }, async object => object.id)",
    "const bound: number = createCapabilityEvaluator().readPrivate('adoption.application.readPrivate', { count: 1 }, object => object.count)",
    "const fresh: number = readPrivate('adoption.application.readPrivate', { object: { count: 1 }, readObject: () => ({ count: 2 }) }, object => object.count)",
    "declare const emitSearch: InstanceType<typeof Search>['$emit']",
    "declare const emitShare: InstanceType<typeof Share>['$emit']",
    "declare const emitFixed: InstanceType<typeof FixedBar>['$emit']",
    "declare const emitComments: InstanceType<typeof Comments>['$emit']",
    "declare const toast: InstanceType<typeof Toast>",
    "declare const adoptPicker: InstanceType<typeof AdoptPickCatsSheet>",
    "emitSearch('input', '猫'); emitSearch('search', '猫'); emitShare('select', 'link', { path: '/page' }); emitFixed('primary', { key: 'feed', label: '投喂' }); emitComments('like', { id: 'c' })",
    "toast.show('保存成功', 1200)",
    "adoptPicker.normalizeAdoptionValue(15); adoptPicker.normalizeAdoptionValue('15'); const gridProps: InstanceType<typeof NineGrid>['$props'] = { NineGridList: ['/cat.png'] }; void gridProps",
    "declare const regionPicker: InstanceType<typeof PawRegionPicker>; regionPicker.initialize(['湖南省']); declare const yardCreatePage: InstanceType<typeof YardCreatePage>; yardCreatePage.doTrim(' 小院'); declare const feedingDetailPage: InstanceType<typeof FeedingOrderDetailPage>; feedingDetailPage.normalizeVariant('91'); feedingDetailPage.normalizePerspective('yard'); const recorderStopEvent: YardRecorderStopEvent = { duration: 1000, tempFilePath: '/tmp/record.mp3' }; void recorderStopEvent; const selectionProps: InstanceType<typeof PawSelectionSheet>['$props'] = { items: ['猫', 1, { label: '犬' }] }; void selectionProps; getAdoptionReviewList({ tab: 'pending', reviewerRole: 'owner', reviewerId: 'user-1' }); declare const imageCropper: InstanceType<typeof PawImageCropper>; imageCropper.onTouchStart(new Event('touchstart')); declare const addressForm: InstanceType<typeof AddressForm>; addressForm.applyWechatAddress({ errMsg: 'ok', userName: 'A', postalCode: '', provinceName: '', cityName: '', countyName: '', detailInfo: '', nationalCode: '', telNumber: '' }); declare const animalDetailPage: InstanceType<typeof AnimalDetailPage>; animalDetailPage.refreshAnimal('pet-1'); animalDetailPage.previewPetImage({ current: '/cat.png', urls: ['/cat.png'] }); declare const albumPage: InstanceType<typeof AnimalAlbumPage>; albumPage.openAlbumMenu(createAnimalAlbumItems()[0], new Event('longpress')); declare const adoptionReviewDetail: InstanceType<typeof AdoptionReviewDetailPage>; adoptionReviewDetail.resolveReviewerRole('owner', 'user-1', null); declare const adoptionJuryDetail: InstanceType<typeof AdoptionJuryDetailPage>; adoptionJuryDetail.normalizeReviewType('adoption')",
    "const props: InstanceType<typeof Marquee>['$props'] = { items: ['公告', { id: 'a', text: '公告', feedingWeightJin: 4 }] }",
    "getMockFeedingOrderDetail({ type: 'yard-owner', orderId: 'order-1' })",
    "const feedingItem: FeedingOrderItem = { id: 'order-1', stateKey: 'active', petTags: ['亲人'] }; void feedingItem; writeRewardOrders([{ id: 'reward-1', applicationId: 'application-1', recordId: 'application-1' }]); findRegionOptions(['湖南省']); findRegionPath(['安徽省', '合肥市'])",
    "formatFeedbackTimeout('2026-01-01T00:00:00.000Z'); formatFeedbackTimeout(Date.now())",
    "getPawHomeYardPetById('pet-1')",
    "getFeedingOrderDetail({ type: 'yard-owner', orderId: 'order-1' })",
    "getServiceFeedingOrders({ variant: 'yard', sort: 'newest' })",
    "setOrderHidden('order-1', true, { actorProvider: () => null })",
    "hideOrderForUser('order-1', { actorProvider: () => null })",
    "getAddressById('address-1'); deleteAddress('address-1'); setDefaultAddress('address-1')",
    "setRealNameVerified(true); getMemberLevelTitle(5); getMemberLevelTitle('5')",
    "getJuryVote('jury-1'); writeJuryVote('jury-1', 'real'); writeJuryVotes({ 'jury-1': 'fake' }); getJuryItemsByStatus('pending'); getJuryItemById('jury-1'); getNextJuryItem('jury-1', { items: [] }); getJuryMockItemById('jury-1'); getJuryMockConfig({ dailyVoteLimit: 5 })",
    "readPublicProfile('user-1'); updateLocalProfile('user-1', { name: 'A', tags: ['helper'] }); readOrderById('order-1'); readGiftOrderByApplicationId('application-1'); findRewardOrderById('order-1'); findRewardOrderByApplicationId('application-1'); getAdoptionById('application-1'); setLastAdoptionId('application-1'); getRescueById('rescue-1'); addAdoption({ status: 'pending', pets: [] }); updateAdoption('application-1', { status: 'pending' }); transitionAdoption('application-1', 'cloud_pending'); createRescue({ applicationStatus: 'platform_pending' }); updateRescue('rescue-1', { amount: 10 }); transitionRescueApplication('rescue-1', 'platform_approved'); addRescueProof('rescue-1', { name: 'A', story: '说明', createdAt: Date.now() }); hasRescueProofByUser('rescue-1', 'actor-1'); canManageRescue('rescue-1', 'actor-1', ['admin']); getRescueReviewSummary([])",
    "const orderList: Promise<OrderResult<OrderListData>> = readOrderList(); declare const orderResult: OrderResult<OrderListData>; if (!orderResult.success) { const errorData: OrderListData | null = orderResult.data; void errorData }",
    "saveRewardOrder({ orderId: 'reward-1', orderType: 'adoption_gift', applicationId: 'application-1', userId: 'user-1', status: 'submitted' }, { readOrders: () => [], writeOrders: orders => orders.length > 0 })",
    "findGiftOrderByApplicationId([{ orderId: 'reward-1', orderType: 'adoption_gift', applicationId: 'application-1', userId: 'user-1', status: 'submitted' }], 'application-1'); rewardAssociationKey('application-1'); visibilityKey('user-1', 'order-1'); isOrderHiddenForUser([{ userId: 'user-1', orderId: 'order-1', hidden: true }], 'user-1', 'order-1'); canOrderAction(ORDER_OPERATIONS.PAY, { orderId: 'order-1', orderType: 'normal_feed', userId: 'user-1', status: 'pending_payment' }, { id: 'user-1', roles: [] })",
    "getAdoptionMineStatusTone('green'); getAdoptionQuotaTitle('quota-detail'); getRescueApplicationStatusPresentation('platform_pending'); getRescueMineStatusPresentation('platform_pending'); createFeedingOrderToolbarState('', 'newest')",
    "readRescueReviewList({ filter: 'all', actorProvider: () => null, reader: () => [] })",
    "readRescueReviewDetail({ reviewItemId: 'review-1', actorProvider: () => null, reader: () => [] })",
    "applyRescueReviewAction({ reviewItemId: 'review-1', outcome: 'approved', idempotencyKey: 'action-1', actorProvider: () => null, reader: () => [], writer: context => { const action: 'approved' | 'rejected' = context.action; const record = { ...context.next }; void action; void record } })",
    "const deepLink = resolveProductionDeepLink({ businessType: 'rescue', businessId: 'rescue-1' }); if (deepLink.status === 'ready') { const target: string = deepLink.target.routeName; const record: Record<string, unknown> | null = deepLink.record; void target; void record }",
    "const target = createDeepLink({ businessType: 'rescue', businessId: 'rescue-1' }); createTaskDeepLink({ businessType: 'rescue', businessId: 'rescue-1' }); restoreAfterAuth(target, { authenticated: true }); saveAuthContinuation({ target, messageId: 'message-1', category: 'system' }); feedbackBusinessKey({ kind: 'dynamic', dynamicId: 'dynamic-1', actorId: 'user-1', policyVersion: 'v1', attemptKey: 'try-1' }); feedbackRequestKey({ kind: 'feeding_evidence', orderId: 'order-1', animalId: 'animal-1', yardId: 'yard-1', actorId: 'user-1', policyVersion: 'v1', attemptKey: 'try-1', requestId: 'request-1' })",
    "evaluateSocialMutation({ intent: 'delete', dynamicId: 'dynamic-1', commentId: 'comment-1', record: { dynamicId: 'dynamic-1', commentId: 'comment-1', authorId: 'user-1' }, actorProvider: () => ({ actor: { id: 'user-1', roles: [] } }) }); readPawImageSourceUrl({ src: '/cat.png' }); readCompressedPawImageUrl({ tempFilePath: '/tmp/cat.png' }); normalizePawImageDisplayMode('fixed')",
    "createApplication('adoptoin', {}) // invalid",
    "createApplication('adoption', { pets: 123 }) // invalid",
    "createApplication('adoption', { mediaPaths: [false] }) // invalid",
    "createApplication('adoption', { amount: 10 }) // invalid",
    "createApplication('rescue', { applicationStatus: 'made-up' }) // invalid",
    "getPetRoster({ species: 'dragon' }) // invalid",
    "getPetRoster({ managed: { oops: true } }) // invalid",
    "getFeedingOrders({ sort: 'made-up' }) // invalid",
    "formatFeedbackTimeout({ timestamp: 'yesterday' }) // invalid",
    "getPawHomeYardPetById({ id: 'pet-1' }) // invalid",
    "const invalidFeedingItem: FeedingOrderItem = { id: 'order-1', stateKey: 'active', petTags: [false] } // invalid",
    "writeRewardOrders([{}]) // invalid",
    "findRegionOptions([1]) // invalid",
    "findRegionPath([{}]) // invalid",
    "declare const orderFailure: OrderResult<OrderListData>; if (!orderFailure.success) { const invalidErrorData: string = orderFailure.data } // invalid",
    "saveRewardOrder({ orderId: 'order-1', orderType: 'normal_feed', userId: 'user-1', status: 'submitted' }) // invalid",
    "saveRewardOrder({ orderId: 'reward-1', orderType: 'adoption_gift', userId: 'user-1', status: 'submitted' }) // invalid",
    "saveRewardOrder({ orderId: 'reward-1', orderType: 'adoption_gift', applicationId: 'application-1', userId: 'user-1', status: 'submitted' }, { readOrders: 123 }) // invalid",
    "findGiftOrderByApplicationId({}, 'application-1') // invalid",
    "findGiftOrderByApplicationId([], {}) // invalid",
    "rewardAssociationKey({}) // invalid",
    "visibilityKey({}, 'order-1') // invalid",
    "isOrderHiddenForUser([], 'user-1', {}) // invalid",
    "canOrderAction('write', { orderId: 'order-1', orderType: 'normal_feed', userId: 'user-1', status: 'completed' }, { id: 'user-1', roles: [] }) // invalid",
    "getAdoptionMineStatusTone({ status: 'green' }) // invalid",
    "getAdoptionQuotaTitle('unknown-mode') // invalid",
    "getRescueApplicationStatusPresentation({ status: 'platform_pending' }) // invalid",
    "getRescueMineStatusPresentation('pending') // invalid",
    "createFeedingOrderToolbarState('', 'untrusted-sort') // invalid",
    "getMockFeedingOrderDetail({ type: 'yard-owner-ish' }) // invalid",
    "getMockFeedingOrderDetail({ orderId: {} }) // invalid",
    "getFeedingOrderDetail({ type: 'yard-owner-ish' }) // invalid",
    "getServiceFeedingOrders({ variant: 'animal' }) // invalid",
    "getServiceFeedingOrders({ sort: 'price' }) // invalid",
    "setOrderHidden({}, true) // invalid",
    "setOrderHidden('order-1', 'yes') // invalid",
    "setOrderHidden('order-1', true, { actorProvider: 123 }) // invalid",
    "hideOrderForUser({}, { actorProvider: () => null }) // invalid",
    "getAddressById({}) // invalid",
    "deleteAddress(123) // invalid",
    "setDefaultAddress(null) // invalid",
    "setRealNameVerified('yes') // invalid",
    "getMemberLevelTitle(false) // invalid",
    "writeJuryVote({}, 'real') // invalid",
    "writeJuryVote('jury-1', 'maybe') // invalid",
    "writeJuryVotes({ 'jury-1': 'maybe' }) // invalid",
    "getJuryItemsByStatus('all') // invalid",
    "getJuryItemById({}) // invalid",
    "getNextJuryItem('jury-1', { items: ['bad'] }) // invalid",
    "getJuryMockItemById(1) // invalid",
    "getJuryMockConfig({ dailyVoteLimit: 'many' }) // invalid",
    "readPublicProfile({}) // invalid",
    "updateLocalProfile('user-1', { role: 'admin' }) // invalid",
    "readOrderById({}) // invalid",
    "readGiftOrderByApplicationId(1) // invalid",
    "findRewardOrderById({}) // invalid",
    "findRewardOrderByApplicationId(null) // invalid",
    "getAdoptionById({}) // invalid",
    "setLastAdoptionId(12) // invalid",
    "getRescueById(false) // invalid",
    "addAdoption({ status: 'platform_pending' }) // invalid",
    "updateAdoption({}, { status: 'pending' }) // invalid",
    "transitionAdoption('application-1', 'platform_approved') // invalid",
    "createRescue({ status: 'owner_pending' }) // invalid",
    "updateRescue('rescue-1', { amount: 'ten' }) // invalid",
    "transitionRescueApplication('rescue-1', 'pending') // invalid",
    "addRescueProof('rescue-1', { createdAt: {} }) // invalid",
    "hasRescueProofByUser({}, 'actor-1') // invalid",
    "canManageRescue('rescue-1', 12) // invalid",
    "readRescueReviewList({ filter: 'made-up' }) // invalid",
    "readOrderList({ actorProvider: { id: 'user-1' } }) // invalid",
    "readOrderList({ source: 'gift' }) // invalid",
    "readRescueMine({ filter: 'unknown' }) // invalid",
    "readRescueMine({ resolver: 123 }) // invalid",
    "createAdoptionTransitionContract({ pending: [1] }) // invalid",
    "getFeedbackTaskAccess({ actorId: 123 }) // invalid",
    "readRescueReviewDetail({ reviewItemId: {} }) // invalid",
    "applyRescueReviewAction({ reviewItemId: 'review-1', outcome: 'approve-ish', idempotencyKey: 'action-1' }) // invalid",
    "applyRescueReviewAction({ reviewItemId: 'review-1', outcome: 'approved', idempotencyKey: 'action-1', writer: 123 }) // invalid",
    "applyRescueReviewAction({ reviewItemId: 'review-1', outcome: 'approved', idempotencyKey: 'action-1', writer: context => context.notAField }) // invalid",
    "resolveProductionDeepLink({}).stauts // invalid",
    "createDeepLink({ businessType: 'rescue', businessId: 123 }) // invalid",
    "createTaskDeepLink({ businessType: 'rescue', businessId: 'rescue-1', source: 'external' }) // invalid",
    "restoreAfterAuth({}, { authenticated: false }) // invalid",
    "saveAuthContinuation({ target: {} }) // invalid",
    "saveAuthContinuation({ target: { businessType: 'rescue', businessId: 'rescue-1' }, category: 'mail' }) // invalid",
    "feedbackBusinessKey({ kind: 'dynamic', dynamicId: 'dynamic-1', actorId: 'user-1', policyVersion: 'v1', attemptKey: 42 }) // invalid",
    "feedbackBusinessKey({ kind: 'feeding_evidence', dynamicId: 'dynamic-1', actorId: 'user-1', policyVersion: 'v1', attemptKey: 'try-1' }) // invalid",
    "feedbackRequestKey({ kind: 'dynamic', dynamicId: 'dynamic-1', actorId: 'user-1', policyVersion: 'v1', attemptKey: 'try-1' }) // invalid",
    "evaluateSocialMutation({ intent: 'restore', dynamicId: 'dynamic-1', commentId: 'comment-1', record: { dynamicId: 'dynamic-1', commentId: 'comment-1' }, actorProvider: () => null }) // invalid",
    "evaluateSocialMutation({ intent: 'delete', dynamicId: 'dynamic-1', commentId: 'comment-1', record: {}, actorProvider: () => null }) // invalid",
    "evaluateSocialMutation({ intent: 'delete', dynamicId: 'dynamic-1', commentId: 'comment-1', record: { dynamicId: 'dynamic-1', commentId: 'comment-1' }, actorProvider: 123 }) // invalid",
    "readPawImageSourceUrl(123) // invalid",
    "readCompressedPawImageUrl({ path: '/tmp/cat.png' }) // invalid",
    "normalizePawImageDisplayMode({ mode: 'fixed' }) // invalid",
    "readProfile({}) // invalid",
    "readYard(1) // invalid",
    "readManagementResource('horse', 'id') // invalid",
    "readManagement({ resourceType: 'yard', userId: 'user-1' }) // invalid",
    "readProfile('user-1', { access: 'write' }) // invalid",
    "readManagementResourceWithReader('yard', 'yard-1', { reader: 123 }) // invalid",
    "readManagementResourceWithReader('profile', 'user-1', { reader: locator => locator.notAField }) // invalid",
    "createManagementAdapter({ readers: { yard: 123 } }) // invalid",
    "updateProfile({}, { nickname: 'A' }) // invalid",
    "updateProfile('user-1', { role: 'admin' }) // invalid",
    "updateYard('yard-1', { ownerId: 'other' }) // invalid",
    "updateAnimal('animal-1', { location: 'nowhere' }) // invalid",
    "updateManagementResource('profile', 'user-1', { breed: 'cat' }) // invalid",
    "updateProfile('user-1', { nickname: 'A' }, { writer: () => 'saved' }) // invalid",
    "updateProfile('user-1', { nickname: 'A' }, { writer: async () => true }) // invalid",
    "readEditorResource('yard', {}) // invalid",
    "saveEditorResource('animal', 'animal-1', { yardId: 'other-yard' }) // invalid",
    "readPublicYard({}) // invalid",
    "updateLocalYard('yard-1', { ownerId: 'other' }) // invalid",
    "readPublicAnimal('animal-1', { yardId: 123 }) // invalid",
    "readAdoptionApplicationWithResolver({}, { actorProvider: () => null, resolver: () => ({}) }) // invalid",
    "readAdoptionApplicationWithResolver('application-1', { actorProvider: 123, resolver: () => ({}) }) // invalid",
    "readAdoptionApplicationWithResolver('application-1', { actorProvider: () => null, perspective: 'reviewer', resolver: () => ({}) }) // invalid",
    "readAdoptionReviewList({ filter: 'queued' }) // invalid",
    "readAdoptionReviewDetail({ applicationId: {}, reviewItemId: 'review-1' }) // invalid",
    "readAdoptionReviewList({ reviewerRole: 'applicant' }) // invalid",
    "readRescueStateById(123) // invalid",
    "readRescueStateById('rescue-1', { includeDemo: 'yes' }) // invalid",
    "readRescueStateWithResolver('rescue-1', { resolver: context => context.missing }) // invalid",
    "readRescueMine({ filter: 'resolved' }) // invalid",
    "readRescueMine({ actorProvider: null }) // invalid",
    "readAccountTasks({ readers: { dragon: () => [] } }) // invalid",
    "readAccountTasks({ readers: { adoption: 123 } }) // invalid",
    "readDynamicRecord(false) // invalid",
    "readDynamicRecord('dynamic-1', { requireActor: 'false' }) // invalid",
    "getFeedingOrderPicker({ variant: 'animal' }) // invalid",
    "animalIdsOfOrder(null) // invalid",
    "isFeedbackEligible('delivered') // invalid",
    "getFeedingOrderPicker({ yardId: 12 }) // invalid",
    "readPersistedOrderDetail(123, { actorProvider: () => null }) // invalid",
    "readPersistedOrderDetail('order-1', { actorProvider: () => null, hiddenEntries: [{ userId: 'u', orderId: 'o', hidden: 'yes' }] }) // invalid",
    "readFeedbackTaskList({ actorProvider: () => null, kind: 'other' }) // invalid",
    "readFeedbackTaskList({ actorProvider: () => null, kind: 'dynamic', perspective: 'reviewer' }) // invalid",
    "readFeedbackTaskDetail({ actorProvider: () => null, kind: 'dynamic', taskId: 42 }) // invalid",
    "readFeedbackTaskList({ actorProvider: () => null, kind: 'dynamic', reader: context => context.missing }) // invalid",
    "submitRescueProof('rescue-1', { name: 'A', relation: '邻居', note: '说明', idNo: 12, agreementChecked: true }) // invalid",
    "submitRescueProof({}, { name: 'A', relation: '邻居', note: '说明', idNo: '11010519491231002X', agreementChecked: true }) // invalid",
    "readFeedbackEvidence({ actorProvider: 123, policy: feedbackPolicy }) // invalid",
    "appendFeedbackEvidence({ evidenceId: 'e', dynamicId: 'd', kind: 'dynamic', actorId: 'a', policyVersion: 'v1', attemptKey: 'k', requestId: 'r', state: 'made-up', createdAt: 'today' }, { actorProvider: () => null, policy: feedbackPolicy }) // invalid",
    "readFeedingTaskSummaries({ actorProvider: null }) // invalid",
    "readMessageById(12) // invalid",
    "appendMessage({ messageId: 'm', recipientId: 'u', category: 'system', title: '通知', preview: '', createdAt: 'now', businessType: 'adoption', businessId: 'a' }, { authorize: 123 }) // invalid",
    "resolveMessageDestination('m', { readers: { dragon: () => ({}) } }) // invalid",
    "resolveMessageDestination('m', { readers: { adoption: context => context.notAField } }) // invalid",
    "produceLocalActionNotification({ action: {}, recipientId: 'u', businessType: 'adoption', businessId: 'a', title: '通知' }) // invalid",
    "produceLocalActionNotification({ action: { success: true, actorId: 'u' }, recipientId: 'u', businessType: 'adoption', businessId: 'a', title: '通知', category: 'unknown' }) // invalid",
    "publishLocalFeedback({ content: 123 }) // invalid",
    "const invalidFailureData: string = dynamicPublishFailure.data // invalid",
    "publishLocalDynamic({ content: '动态', attemptKey: {}, dynamicId: 'dynamic-1' }) // invalid",
    "publishLocalFeedback({ mediaList: [false] }) // invalid",
    "publishLocalFeedback({ storage: { getStorageSync: () => null } }) // invalid",
    "readLocalFeedbackSummary({ order: 'order-1' }) // invalid",
    "readAdoptionProgress(123) // invalid",
    "statusPresentation({ status: false }) // invalid",
    "statusPresentation('pending') // invalid",
    "proofCount({ evidenceCount: 'many' }) // invalid",
    "normalizedProofList({ proofList: [] }) // invalid",
    "recognizeAddress({ text: '张三' }) // invalid",
    "parseAddressLocally(123) // invalid",
    "getAnnouncementFeedingWeightJin('投喂4斤') // invalid",
    "asPawImageCssSize({ width: 32 }) // invalid",
    "createDynamicMediaViewerItems([false], '/fallback.png') // invalid",
    "readRescueProgress({}, { actorProvider: 123 }) // invalid",
    "updateLocalAnimal('animal-1', { birthday: '2020-01-01' }) // invalid",
    "updateLocalAnimal('animal-1', { species: 'dragon' }) // invalid",
    "createLocalAnimal('yard-1', { breed: '英短' }) // invalid",
    "createLocalAnimal(1, { name: 'Mimi', breed: '英短' }) // invalid",
    "readYardEditorGate('animal', 'yard-1') // invalid",
    "readAnimalEditorGate('animal-1') // invalid",
    "if (result.success) { result.data.stauts } // invalid",
    "updateApplication('adoption', 'a', { stauts: 'pending' }) // invalid",
    "advanceApplication('adoption', 'a', 'platform_approved') // invalid",
    "advanceApplication('adoption', 'a', 'unknown') // invalid",
    "const status = getApplicationStatus('adoption', 'a'); if (status.success) { const wrong: number = status.data.status } // invalid",
    "readPrivate('adoption.application.readPrivate', { object: { count: 1 } }, 123) // invalid",
    "readPrivate('adoption.application.readPrivate', { object: { count: 1 } }, object => object.missing) // invalid",
    "const wrong: string = readPrivate('adoption.application.readPrivate', { object: { count: 1 } }, object => object.count) // invalid",
    "readPrivate('made-up', { object: {} }, () => true) // invalid",
    "emitSearch('input', 42) // invalid",
    "emitSearch('search') // invalid",
    "emitShare('select', 'unknown', {}) // invalid",
    "emitFixed('primary', { key: 123 }) // invalid",
    "emitComments('like', { id: false }) // invalid",
    "toast.show({}, 1200) // invalid",
    "toast.show('保存成功', '1200') // invalid",
    "adoptPicker.normalizeAdoptionValue({ value: 15 }) // invalid",
    "regionPicker.initialize([1]) // invalid",
    "yardCreatePage.doTrim(15) // invalid",
    "feedingDetailPage.normalizeVariant({}) // invalid",
    "feedingDetailPage.normalizePerspective(91) // invalid",
    "getAdoptionReviewList({ tab: 'unknown', reviewerRole: 15 }) // invalid",
    "imageCropper.onTouchStart('touchstart') // invalid",
    "addressForm.applyWechatAddress({ userName: 'A' }) // invalid",
    "animalDetailPage.refreshAnimal(123) // invalid",
    "albumPage.openAlbumMenu(createAnimalAlbumItems()[0], 'longpress') // invalid",
    "adoptionReviewDetail.resolveReviewerRole({}, 1, null) // invalid",
    "adoptionJuryDetail.normalizeReviewType(1) // invalid",
    "const invalidRecorderStopEvent: YardRecorderStopEvent = { duration: '1000' } // invalid",
    "const invalidGridProps: InstanceType<typeof NineGrid>['$props'] = { NineGridList: [false] } // invalid",
    "const badProps: InstanceType<typeof Marquee>['$props'] = { items: [false] } // invalid",
    "const snapshot = readAdoptionApplication('a'); if (snapshot.data) { snapshot.data.stauts } // invalid",
  ]
  const expected = source.flatMap((line, index) => line.endsWith('// invalid') ? [index + 1] : [])
  await fs.writeFile(path.join(dir, 'consumer.ts'), source.join('\n'))
  await fs.writeFile(path.join(dir, 'tsconfig.json'), JSON.stringify({
    extends: '../../tsconfig.json',
    compilerOptions: { noUnusedLocals: false, noUnusedParameters: false },
    include: ['consumer.ts', '../../env.d.ts', '../../shims-uni.d.ts'], exclude: [],
  }, null, 2))
  let output = ''
  try {
    execFileSync(process.execPath, [path.join(ROOT, 'node_modules/vue-tsc/bin/vue-tsc.js'), '--noEmit', '--pretty', 'false', '-p', path.join(dir, 'tsconfig.json')], { cwd: ROOT, encoding: 'utf8', stdio: 'pipe' })
    assert.fail('invalid consumers unexpectedly compiled')
  } catch (error) {
    assert.equal(error.status, 2, error.stderr || error.message)
    output = error.stdout
  }
  await fs.writeFile(path.join(dir, 'consumer-diagnostics.log'), output)
  const actual = [...output.matchAll(/consumer\.ts\((\d+),\d+\): error TS\d+:/g)].map(match => Number(match[1]))
  assert.deepEqual([...new Set(actual)].sort((a, b) => a - b), expected, output)
  const otherErrors = output.split('\n').filter(line => /: error TS\d+:/.test(line) && !line.includes('consumer.ts('))
  assert.deepEqual(otherErrors, [], output)
})

test('storage parsers sanitize media and timestamps and preserve invalid-state diagnostics', async () => {
  const adoption = await import(pathToFileURL(path.join(ROOT, 'utils/adoptionStorage.ts')).href)
  const rescue = await import(pathToFileURL(path.join(ROOT, 'utils/rescueStorage.ts')).href)
  const a = adoption.normalizeAdoptionRecord({ id: 'a', status: 'made-up', mediaPaths: ['/a.png', false, 1, {}], proofPhotos: [null, '/proof.png'], reapproval: { lastAt: {} }, createdAt: {} })
  assert.equal(a.status, 'unknown')
  assert.deepEqual(a.mediaPaths, ['/a.png'])
  assert.deepEqual(a.proofPhotos, ['/proof.png'])
  assert.equal(a.reapproval.lastAt, null)
  assert.equal(a.createdAt, null)
  assert.equal(Object.hasOwn(a, 'applicationId'), false)
  const r = rescue.normalizeRescueRecord({ id: 'r', status: 'approved', applicationStatus: 'platform_approved', createdAt: 123, media: [false, {}, '/r.png'] })
  assert.equal(r.status, 'approved')
  assert.equal(r.createdAt, 123)
  assert.deepEqual(r.mediaPaths, ['/r.png'])
  assert.equal(rescue.normalizeRescueRecord({ id: 'r', applicationStatus: 'made-up' }).applicationStatus, 'unknown')
})
